---
resources:
- name: go-library-source
  type: git
  source:
    uri: https://github.com/ricky-clevinger/12FactorGoAPI
    branch: master

- name: library-deploy
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-username}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: true
    
- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/ricky-clevinger/Versions
    username: ricky-clevinger
    password: 123098Rlc
    branch: master
    file: 12FactorGoLibrary
    
jobs:
- name: unit-test-go
  serial: true
  plan:
  - get: go-library-source
    trigger: true
  - task: go-unit-tests
    file: go-library-source/src/12FactorGoAPI/ci/goUnitTest.yml
    privileged: true
    
- name: deploy
  serial: true
  plan:
  - get: go-library-source
    passed: [ unit-test-go ]
    trigger: true
  - task: build-deploy-go-library
    file: go-library-source/src/12FactorGoAPI/ci/build.yml
    privileged: true
  - put: library-deploy
    params:
       manifest: go-library-source/src/12FactorGoAPI/manifest.yml
       path: go-library-source/src/12FactorGoAPI
