---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "latest"
    
inputs:
- name: go-library-source

outputs:
- name: built-project

run:
  path: go-library-source/src/ci/build.sh
